#!/bin/sh

self="${0#./}"
base="${self%/*}"
current=$(pwd)

if [ "$base" = "$self" ] ; then
	path=$current
else
	path=$base
fi ;

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$path/lib
export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:$path/lib
export PATH=$path/bin/lua/bin:$PATH

#lua -joff -luatrace.profile $path/bin/brat $@
lua -jannotate $path/bin/brat $@
#lua -jdump $path/bin/brat $@
#lua $path/bin/brat $@
