#!/bin/sh

self="${0#./}"
base="${self%/*}"
current=$(pwd)

if [ "$base" = "$self" ] ; then
	path=$current
else
	path=$base
fi ;

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$path/lib:$path/bin/lua/lib/
export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:$path/lib
export PATH=$path/bin/lua/bin:$PATH

if [ `uname` = "Darwin" ]
then
  $path/bin/minibrat-osx $@
else
  $path/bin/minibrat $@
fi
